name: coba
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  build_runner: ^2.4.0
  connectivity_plus: ^6.0.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.7.0
  go_router: ^14.2.3
  http: ^1.2.2
  mockito: ^5.4.4
  google_fonts: ^6.1.0
  flutter_secure_storage: ^8.1.0
  flutter_bloc: ^8.1.3
  another_flushbar: ^1.12.30
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/images/

